### ISSUE TITLE
Authenticating with Google fails

### ISSUE THREAD

**Issue by alexmuller** [edds/browser-matrix#1]
> 400. That’s an error.
> 
> Error: redirect_uri_mismatch
> 
> Application: BrowserMatrix
> 
> The redirect URI in the request: https://edds.github.io/browser-matrix/ did not match a registered redirect URI
> 
> Request Details
> 
> ```
> scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/analytics.readonly
> response_type=token
> redirect_uri=https://edds.github.io/browser-matrix/
> approval_prompt=auto
> state=
> client_id=85453278104.apps.googleusercontent.com
> ```

:disappointed:

**Comment by edds** [comment]
Damn, hadn't added https as an allowed option. Fixed.

**Comment by alexmuller** [comment]
Aha, I couldn't figure out why it was working on one computer but not another. Thanks!
